### ISSUE TITLE
Change Nav-bar component

### ISSUE THREAD

**Issue by priyanshu0405** [GeekHaven/vaprco#15]
Change the "BLOG" component of nav-bar to "TEAM".
changes to be made in ` vaprco/src/components/Nav.svelte `

**Comment by Mehul-12** [comment]
Interested, pl assign.

**Comment by naina24** [comment]
May I work on this??

**Comment by priyanshu0405** [comment]
Assigning this to @Mehul-12. hey @naina24, would you like to take #17 .
