### ISSUE TITLE
Make profile card Template

### ISSUE THREAD

**Issue by priyanshu0405** [GeekHaven/vaprco#17]
Make Profile card template for Team page.

**Comment by naina24** [comment]
May I work on this??

**Comment by naina24** [comment]
Interested

**Comment by naina24** [comment]
Interested

**Comment by priyanshu0405** [comment]
@naina24 sure go ahead. I had a few templates in mind I could share them on the discord channel of Geektoberfest.

**Comment by naina24** [comment]
I got that template. I am trying to do like that.

**Comment by naina24** [comment]
I am new to Svelet so could you please tell me in which file do I have to code.

**Comment by naina24** [comment]
Before I got your template I was thinking about this https://codepen.io/aniketx27/pen/pGoYGR.Once have a look

**Comment by naina24** [comment]
Before I got your template I was thinking about this https://codepen.io/aniketx27/pen/pGoYGR .Once have a look

**Comment by naina24** [comment]
Before I got your template I was thinking about this https://codepen.io/aniketx27/pen/pGoYGR .Once have a look please.

**Comment by priyanshu0405** [comment]
Hey @naina24, `vaprco/src/routes/blog/index.svelte` this is the file you have to make changes in. Also sync your fork first because the theme has been changed. I think the one I send you goes well with the theme, let's go with that. For any other doubts you can ping me on the discord channel.

**Comment by kumarmanish03** [comment]
Hey, Is it still open, If open kindly assign to me, I will make pr soon
