### ISSUE TITLE
Add title

### ISSUE THREAD

**Issue by priyanshu0405** [GeekHaven/vaprco#18]
Add the title "Our Team" to BLOG page
Changes to be made in `vaprco/src/routes/blog/index.svelte`

**Comment by Cypherdious89** [comment]
Can I do this @priyanshu0405 ?

**Comment by priyanshu0405** [comment]
@Priyansh-09 sure. Let me know if you face any problem.

**Comment by Cypherdious89** [comment]
Hey, @priyanshu0405 please assign someone else 😅
It's taking more time than I expected. I'm not much familiar to Svelte as well.

**Comment by aarpit1010** [comment]
can I try?
@priyanshu0405

**Comment by priyanshu0405** [comment]
@aarpit1010 sure, go ahead.
