### ISSUE TITLE
Change Footer icon size

### ISSUE THREAD

**Issue by priyanshu0405** [GeekHaven/vaprco#33]
Make the footer icon size small.

**Comment by wiktorwojcik112** [comment]
Hi. Can I try to do this?

**Comment by therealansh** [comment]
Hey Can i do this?

**Comment by priyanshu0405** [comment]
@wiktorwojcik112  this a college event for learning we can only allow our college students. @therealansh go ahead.

**Comment by wiktorwojcik112** [comment]
Sorry. Good luck!
