### ISSUE TITLE
Enhancement of navigation-bar

### ISSUE THREAD

**Issue by priyanshu0405** [GeekHaven/vaprco#6]
Shift the navbar contents to the right. Change the color and add hover effect to the components.
Changes to be made in  `vaprco/src/components/Nav.svelte `.

**Comment by geeks5551** [comment]
can i work on this?

**Comment by priyanshu0405** [comment]
@geeks5551, you are not allowed to work on 2 issues of the same repo simultaneously, so first complete the one assigned to you.

**Comment by binismail** [comment]
Hey, Khalid here,

i would like to work on this

@priyanshu0405

**Comment by priyanshu0405** [comment]
Hi @binismail, sorry this repo is for an event of our college and only college students are allowed to participate.

**Comment by naina24** [comment]
May I work on this?

**Comment by naina24** [comment]
I am interested. May I work on this?

**Comment by priyanshu0405** [comment]
Hey @naina24 , sure. Feel free to ask if you face any problem.

**Comment by Mehul-12** [comment]
interested, pl assign.

**Comment by Ranveer251** [comment]
I am interested, Please assign.
