### ISSUE TITLE
Add footer section on Home page

### ISSUE THREAD

**Issue by priyanshu0405** [GeekHaven/vaprco#7]
Also add github, linkedin, instagram, discord, facebook and mail icons in the footer section.
Changes to be made in  `vaprco/src/routes/_layout.svelte `.

**Comment by danisoc** [comment]
Can I give this a try?

**Comment by priyanshu0405** [comment]
Hey @ddaniss, sorry this repo is for an event of our college and only college students are allowed to participate.

**Comment by geeks5551** [comment]
hey can i work on this?

**Comment by priyanshu0405** [comment]
hi @geeks5551, sure. Let me know if you face any problem.

**Comment by geeks5551** [comment]
hey @priyanshu0405 i am facing issues in setting up svelte

**Comment by priyanshu0405** [comment]
@geeks5551 join the discord channel for issues provided in the geekhaven mail

**Comment by Mehul-12** [comment]
interested, pl assign.

**Comment by priyanshu0405** [comment]
Hey @Mehul-12, sure. Feel free to ask if you face any problem.

**Comment by kumarmanish03** [comment]
@priyanshu0405  Is it still open?  I want to work on this

**Comment by priyanshu0405** [comment]
hey @kumarmanish03, @Mehul-12 is working on this. I will add few issues tonight, you can take those.
