### ISSUE TITLE
Enhance home page heading

### ISSUE THREAD

**Issue by priyanshu0405** [GeekHaven/vaprco#8]
Change font and change the heading to "VAPR co.".
Changes to be made in  `vaprco/src/routes/index.svelte`.

**Comment by bineetNaidu** [comment]
I would also like to work in this . feel free to reach me so that i can continue to contribute.

**Comment by priyanshu0405** [comment]
hey @bineetNaidu , sorry this repo is for an event of our college and only college students are allowed to participate.

**Comment by Saggittarius-A** [comment]
i want to work on this.

**Comment by priyanshu0405** [comment]
Hey @iit2019017, sure. Let me know if you face any problem.

**Comment by Saggittarius-A** [comment]
Thanku for assigning me @priyanshu0405

**Comment by Saggittarius-A** [comment]
hey @priyanshu0405, I am getting only this on opening html file.
I am not understanding what exactly i have to do in this.
![Screenshot (63)](https://user-images.githubusercontent.com/57368869/95671200-97dea580-0bb1-11eb-8798-43b4e36f2f95.png)

**Comment by priyanshu0405** [comment]
@iit2019017 , you don't have to run the html file. Instead you have to make changes in `vaprco/src/routes/index.svelte`. For running the website you need to go to the vaprco directory on your terminal and run

`npm install`
`npm run dev`

Open up localhost:3000

**Comment by aarpit1010** [comment]
@priyanshu0405  can I work on this?

**Comment by priyanshu0405** [comment]
@iit2019017 are you still working on the issue or should I assign it to someone else?
