### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by priyanshu0405** [GeekHaven/vaprco#9]
Change title to VAPR co.
Delete unnecessary instructions leaving only the "How to build the project".
Add File structure of this repo in tree form.

**Comment by bineetNaidu** [comment]
I would Like to contribute onto this project. Feel free to assign me this work.

**Comment by priyanshu0405** [comment]
Hey @bineetNaidu , sorry this repo is for an event of our college and only college students are allowed to participate.

**Comment by Codedude1** [comment]
Hey @priyanshu0405 , I would like to work on this.

**Comment by priyanshu0405** [comment]
Hi @Codedude1 , sure. Let me know if you face any problem.
